spring.application.name=ship-fast-sleep-well

togglz.enabled=true
togglz.feature-enums=digital.pragmatech.shipfast.Features
togglz.console.enabled=true
togglz.console.path=/togglz-console
togglz.console.secured=false
