name: Build

on: [push]

jobs:
  build-sample-applications:
    strategy:
      matrix:
        include:
          - talks: fixing-a-broken-window
            java: 21
          - talks: things-i-wish-i-knew-spring-boot-testing
            java: 21
          - talks: testing-spring-boot-applications-demystified
            java: 21
          - talks: stop-fighting-your-spring-boot-tests
            java: 21
          - talks: prompt-it-right
            java: 25
    runs-on: ubuntu-latest
    name: Build the Maven project ${{ matrix.talks }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          distribution: temurin
          cache: maven

      - name: Build the Application
        working-directory: ${{ matrix.talks }}
        run: ./mvnw -B verify
