name: Build

on: [push]

jobs:
  build-sample-applications:
    strategy:
      matrix:
        talks: ['fixing-a-broken-window', 'things-i-wish-i-knew-spring-boot-testing', 'testing-spring-boot-applications-demystified']
    runs-on: ubuntu-22.04
    name: Build the Maven project ${{ matrix.talks }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          java-package: jdk
          distribution: temurin
          cache: maven

      - name: Build the Application
        working-directory: ${{ matrix.talks }}
        run: ./mvnw -B verify
